### ISSUE TITLE
Add Census2020 to list of field types

### ISSUE THREAD

**Issue by barwrede** [arex388/Arex388.Geocodio#9]
Hi, Geocodio has Census2020 as a choice now. Will you add this as a fieldtype for census? Thanks.

**Comment by arex388** [comment]
@barwrede My appologies, somehow I didn't realize you had posted this and I'm 2.5 years late in answering. For what it's worth, I've just released v2.0.0 which includes all of the Census options currently available on the API. It is a complete overhaul and rewrite and does introduce breaking changes, though I believe they're for the better. Take a peek if you're still using this library. Thanks!
